name: Create and publish a npm image

on:
  push:
    branches: ['master']

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          run_install: true
      - name: Install dependencies
        run: pnpm install
      - name: Publish
        run: pnpm publish