name: Create and publish a npm image

on:
  push:
    branches: ['main']

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - name: Install dependencies
        run: pnpm install
      - name: Publish
        run: pnpm publish